# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Jest Mock Test
      run: npm test

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Build
      run: docker build -t nodejsapp .

    - name: Tag
      run: |
        docker tag nodejsapp ${{ secrets.DOCKER_HUB_USERNAME }}/nodejsapp:latest
    - name: Push
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nodejsapp:latest

    # - name: Run
    #   run: |
    #     docker run --restart unless-stopped -p 3000:3000 -d ${{ secrets.DOCKER_HUB_USERNAME }}/nodejsapp:latest